import { defineConfig } from "astro/config";
import { unified } from "@astrojs/markdown-remark";
import { remarkMermaid } from "./src/lib/remark-mermaid.mjs";
import { rehypeExternalLinks } from "./src/lib/rehype-external-links.mjs";
import { rehypeHeadingAnchors } from "./src/lib/rehype-heading-anchors.mjs";
import { SITE_ORIGIN } from "./src/consts.ts";

// https://astro.build/config
export default defineConfig({
  site: SITE_ORIGIN,
  trailingSlash: "ignore",
  // A single sitemap.xml is generated by src/pages/sitemap.xml.js instead of
  // the @astrojs/sitemap integration (which emits sitemap-index.xml).
  integrations: [],
  markdown: {
    // Astro 6 deprecated markdown.remarkPlugins/rehypePlugins in favor of a
    // unified() processor from @astrojs/markdown-remark (it still layers on
    // Astro's defaults: heading IDs, GFM, Shiki).
    processor: unified({
      remarkPlugins: [remarkMermaid],
      rehypePlugins: [rehypeExternalLinks, rehypeHeadingAnchors],
    }),
    shikiConfig: {
      // Dual themes: Shiki emits CSS vars so code adapts to light/dark.
      themes: {
        light: "github-light",
        dark: "github-dark",
      },
      wrap: true,
      // Map the non-standard / wrong-case fence languages used in the original
      // Hashnode posts to real Shiki grammars, so those blocks get highlighted
      // instead of falling back to plaintext.
      langAlias: {
        pgsql: "sql",
        SQL: "sql",
        JS: "javascript",
        env: "ini",
      },
      // Expose the language on the <pre> so the client can render a label.
      transformers: [
        {
          pre(node) {
            node.properties["data-language"] = this.options.lang;
          },
        },
      ],
    },
  },
});
